from flask import Flask, request, jsonify
import pickle
import numpy as np
import os

app = Flask(__name__)

# --- 1. LOAD THE TRAINED MODEL ---
# We use a global variable 'model' to hold our AI brain.
model = None

try:
    # We open the 'model.pkl' file in 'read binary' (rb) mode
    with open('model.pkl', 'rb') as f:
        model = pickle.load(f)
    print("✅ Model loaded successfully!")
except FileNotFoundError:
    print("❌ Error: 'model.pkl' not found. Make sure you uploaded it!")
    # We do not stop the app; we will handle this error inside the predict function if it happens.

# --- 2. THE HOME ROUTE ---
# This is just to check if your server is alive.
@app.route('/')
def home():
    return "Mess Food AI Backend is Running! 🚀"

# --- 3. THE PREDICTION ROUTE ---
# This is where your Flutter app will send data.
@app.route('/predict', methods=['POST'])
def predict():
    try:
        # A. Receive data from Flutter
        data = request.json
        
        # Extract values. We use .get() to prevent crashing if data is missing.
        poll_count = data.get('poll_count', 0)
        is_rainy = data.get('is_rainy', False)

        # B. Check if model is loaded
        if not model:
            return jsonify({'error': 'Model not found on server'}), 500

        # C. Prepare data for the AI
        # The model expects numbers, so we convert True/False to 1/0
        rain_value = 1 if is_rainy else 0
        
        # Scikit-learn expects a list of lists: [[Feature1, Feature2]]
        # This matches how you trained it: [Poll_Count, Is_Rainy]
        features = np.array([[poll_count, rain_value]])

        # D. Ask the Model for a prediction
        prediction_result = model.predict(features)
        
        # The result comes back as an array (e.g., [465.5]). We take the first item.
        final_quantity = int(prediction_result[0])

        # E. Send the answer back to Flutter
        return jsonify({
            'status': 'success',
            'input_received': {
                'poll': poll_count,
                'rain': is_rainy
            },
            'predicted_quantity': final_quantity,
            'message': 'Prediction generated by AI model'
        })

    except Exception as e:
        # If anything breaks, print the error to the logs and tell Flutter
        print(f"Error during prediction: {str(e)}")
        return jsonify({'error': str(e)}), 500

if __name__ == '__main__':
    # This block only runs when you test locally on your laptop
    app.run(debug=True, port=5000)